### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [sensepost/WiFi-Rifle#1]
Nice job!
I'd like to use the wifi.py script and probably make some changes to it...
Can I do that?
What's the license?
I need to know that because I'll be using it as part of my job, so esp. my employer needs to know.

Thanks in advance!

**Comment by marcpeiser** [comment]
Hi there,

The README has been updated with the license, it's licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.

Regards,
Marc

**Comment by ghost** [comment]
Thank you very much for the quick response!
